dist: trusty
language: node_js
node_js:
  - "12"
  - "13"
  - "14"
  - "16"
install:
  - npm install
script: npm run lint && npm run build && npm run build-lib && npm test
cache:
  npm: false
